README.md
=> Update various urls in readme

features/attachments.feature, features/hooks.feature, features/json_formatter.feature, features/scenario_statuses.feature, features/step_definitions/json_output_steps.js, lib/cucumber/listener/json_formatter.js, package.json, spec/cucumber/listener/json_formatter_spec.js
=> json formatter: add match location

features/handling_step_errors.feature, features/step_definitions/file_steps.js, lib/cucumber/support_code/step_definition.js, spec/cucumber/support_code/step_definition_spec.js
Fixes https://github.com/cucumber/cucumber-js/issues/564
=> Fix handling of unusual error objects

README.md
@charlierudolph I had to dig through the code to get this.  https://github.com/cucumber/cucumber-js/blob/7d7ba96262031b4fb7ab83216f474817d3892f3f/lib/cucumber/runtime/scenario_runner.js#L30
and
https://github.com/cucumber/cucumber-js/blob/7d7ba96262031b4fb7ab83216f474817d3892f3f/lib/cucumber/runtime/scenario_runner.js#L43
It might be worth a unit test at some point.
=> Explicit documentation of hook execution order

docs/nodejs_example.md
Fixed the example as it was hitting an invalid url. Hope this helps!
```
Feature: Example feature
As a user of Cucumber.js
I want to have documentation on Cucumber
So that I can concentrate on building awesome applications
Scenario: Reading documentation
✓ Given I am on the Cucumber.js GitHub repository
✓ When I click on "CLI"
✓ Then I should see "Running specific features"
1 scenario (1 passed)
3 steps (3 passed)
0m04.969s
```
=> Use master branch in node.js example

docs/support_files/hooks.md
=> Minor doc fix

docs/support_files/world.md
Sorry, new-ish to github and I can't find my previous PR.
=> fixed typo

docs/support_files/api_reference.md
Fix issue #737 
Update addTransform documentation to use correct parameter name
=> fixes issue #737.  

README.md
Displays the downloads per month, and links to a site that provides more detailed graphs. Nice upward curves btw, keep up the good work!
=> Badge with downloads per month

features/parameter_types.feature
=> parameter type: duplicate regex

docs/support_files/step_definitions.md
updated step_definitions.md docs to remove outdated `this` reference
=> documentation: Updated step_definitions.md

features/cli.feature, features/compiler.feature, features/failed_scenarios.feature, features/failing_steps.feature, features/generator_step_definitions.feature, features/global_install.feature, features/hook_interface.feature, features/hooks.feature, features/parameter_types.feature, features/pretty_formatter.feature, features/register_handler.feature, features/step_wrapper_with_options.feature, features/support/hooks.js, features/support/world.js, features/world_parameters.feature, package.json, src/cli/index.js, src/cli/run.js, yarn.lock
Before:
https://travis-ci.org/cucumber/cucumber-js/builds/246104313
> Ran for 13 min 42 sec
> Total time 31 min 34 sec
After:
https://travis-ci.org/cucumber/cucumber-js/builds/246594033
> Ran for 5 min 54 sec
> Total time 14 min 29 sec
@aslakhellesoy look at what CukenFest did! 🥒💪
=> Invoke CLI in same process as much as possible

CHANGELOG.md, docs/cli.md, features/exit.feature, features/step_definitions/cli_steps.js, features/support/world.js, src/cli/argv_parser.js, src/cli/configuration_builder.js, src/cli/configuration_builder_spec.js, src/cli/index.js, src/cli/run.js
resolves #889 
Copied documentation and interface from https://mochajs.org/#--exit----no-exit
=> wait for event loop to drain

features/custom_formatter.feature, features/snippets_formatter.feature, features/step_definition_snippets.feature, features/step_definition_snippets_i18n.feature, src/formatter/builder.js
=> default to synchronous snippets

docs/cli.md
=> update parallel docs about printing to stdout

CHANGELOG.md, features/order.feature, package.json, src/cli/argv_parser.js, src/cli/configuration_builder.js, src/cli/configuration_builder_spec.js, src/cli/helpers.js, src/cli/helpers_spec.js, src/cli/index.js, src/index.js, yarn.lock
resolves #1031 
Copied the API from cucumber-ruby
=> random feature execution order

CHANGELOG.md, features/gherkin_parse_failure.feature, src/cli/helpers.js
=> improve the error message for gherkin parse errors

docs/support_files/step_definitions.md
=> Add cucumber expressions to step definitions docs.

docs/nodejs_example.md
For someone without package module knowledge, it's not so clear how to install the dependencies with yarn or npm, so, I updated `nodejs_example.md` file with the correct command line.
=> Improvement/updated nodejs_example.md

package.json, yarn.lock
Fixes https://github.com/cucumber/cucumber-js/issues/1238
=> Upgrade to cucumber-expressions 8.0.1

package.json, yarn.lock
=> update cucumber expressions dependency to 8.1.0

README.md
Branch was created from v5.1.0 tag
=> add link to 5.x branch documentation

docs/support_files/world.md
**This pull request updates `world.md` to use `const` instead of `var` and adds some code styling**
=> Updated world.md to use const + some code styling

docs/cli.md, docs/support_files/api_reference.md
Helps address:
- #1245 
- #1139
=> various documentation improvements

docs/support_files/api_reference.md
**This pull request updates documentation for api_reference**
=> docs: update documentation for api_reference

docs/cli.md
This flag was added in https://github.com/cucumber/cucumber-js/pull/424
=> Documenting --fail-fast CLI option

docs/support_files/step_definitions.md
**This pull request updates code examples for step definitions**
=> docs: update code examples for step definitions

docs/cli.md
This behaviour is specified by this test : https://github.com/cucumber/cucumber-js/blob/master/features/strict_mode.feature
=> docs: describe strict mode & --no-strict flag

features/step_definition_snippets_custom_syntax.feature
=> Fix simple typo

docs/custom_snippet_syntaxes.md
Files are now .ts instead of .js
=> docs: Update file link in custom_snippet_syntaxes.md

docs/cli.md, features/parallel.feature, src/cli/argv_parser.ts, src/cli/index.ts, src/runtime/parallel/README.md, src/runtime/parallel/command_types.ts, src/runtime/parallel/coordinator.ts, src/runtime/parallel/run_worker.ts, src/runtime/parallel/worker.ts
=> remove master/slave verbiage

package.json, yarn.lock
Resolving https://github.com/cucumber/cucumber-js/network/alert/yarn.lock/serialize-javascript/open
=> update mocha to resolve security alert

yarn.lock
Removed yarn.lock and recreated to update `nyc#yargs#yargs-parser` to resolve https://github.com/cucumber/cucumber-js/network/alert/yarn.lock/yargs-parser/open
=> update to fix security issue

docs/nodejs_example.md
=> Fix setup docs

docs/support_files/timeouts.md
=> docs: add note about not trying to set default timeout from hooks steps

features/target_specific_scenarios_by_tag.feature
Follow up to #1642 just to make the feature a bit better
=> update tags feature

cucumber.js, features/publish.feature
=> debt: add retry for publish tests

docs/migration.md
=> docs: call out change of after hook result in migration guide

CHANGELOG.md, src/support_code_library_builder/types.ts
IParameterTypeDefinition interface fix
_Why is this change required? What problem does it solve?
Fixes #1702 
- Bug fix (non-breaking change which fixes an issue)
=> IParameterTypeDefinition fix

src/value_checker.ts
See details in commit and commit message.
Partial fix for #1648
- Refactoring/debt (improvement to code design or tooling without
- [ x] My code follows the code style of this project.
- [ x] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [x ] All new and existing tests passed.
=> Make parameter type generic for value checker

README.md
Some minor text styling fixes
Text styling fixes for the sake of consistency
=> docs: minor fixes for the styling consistency

features/i18n.feature, src/cli/i18n.ts
Adds the `Rule` keyword to those we output localised versions of via the `--i18n-keywords <LANG>` option.
Completeness.
Note that we don't need to add `Example` because it's a synonym of `Scenario` and thus already handled.
- Bug fix (non-breaking change which fixes an issue)
- - -
```
ENGLISH KEYWORD  | NATIVE KEYWORDS                                                                                                                                                                                                                                                               
Feature          | "Fonctionnalité" …
```
=> add rule to keywords for i18n command

features/step_definitions/cli_steps.ts
We started the process of replacing regex with cucumber expressions
It's one step towards fixing the issue #1871
- [ x ] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [ x ] My code follows the code style of this project.
=> Replace 1 instance of regex with cucumber expression

docs/profiles.md
Update the profile markdown file.
Documentation needs to mention the changes brought on by ES6 module implementation. Also provided an advanced use case of using profiles to pass arguments to the world cleanly.
- Documentation
=> docs: improve profiles documentation

features/step_definitions/cli_steps.ts
Changed the regular expressions in the step definitions with cucumber expressions
The change is a small step in fixing issue #1871 
- :bank: Refactoring/debt (improvement to code design or tooling without changing behaviour)
=> Replace regexp with cucumber expressions

CHANGELOG.md
* Added links to blog post and upgrade notes to `CHANGELOG`
Because I was looking for them and couldn't find them 😁 
----
=> Add a link to the blog / upgrade notes for v8.0.0

package-lock.json
I ran `npm audit fix`
It's upgraded `async-2.6.3` to `async-2.6.4`
Fix the build.
----
=> Fix dependency audit

docs/configuration.md
Fixed `--publishQuiet` typo. Currently errors
```sh
> cucumber-js --publishQuiet
error: unknown option '--publishQuiet'
(Did you mean --publish-quiet?)
```
Documentation that is correct.
----
=> Fixed `--publishQuiet` typo

docs/formatters.md
Link to Messages updated.
Link to messages was broken.
Documentation
=> [FIX] Messages URL

README.md
Currently the getting started section is incomplete, it could lead the potential user to a frustration since the first run might not be successful.
Let's just update a small information that could bring a major improvment 👍.
Fix #2200 
After following the getting started on the README i though we could improve the onboarding experience.
Great tool 😁
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.m …
=> doc: Update the getting started section on the Readme

features/world_parameters.feature
Modified the feature file error string seek to one compatible with Node 19 without losing compatibility with older node.
Fixes #2218
- [x ] I have added/updated tests to cover my changes.
----
=> Adjust feature file to avoid conflict with new error string of Node 19

package-lock.json, package.json
More information:
* https://github.com/advisories/GHSA-f9xv-q969-pqx4
* https://nvd.nist.gov/vuln/detail/CVE-2023-2251
Fixes #2280
Updated `yaml` depenency to v2.2.2.
Fixes vulnerability:
* https://github.com/advisories/GHSA-f9xv-q969-pqx4
* https://nvd.nist.gov/vuln/detail/CVE-2023-2251
No.
=> Update yaml to v2.2.2 to remedy CVE-2023-2251

src/api/types.ts
Export `ISupportCodeLibrary` from `'@cucumber/cucumber/api'`
Fixes #2283
I'm using this type in StrykerJS.
=> fix(types): export `ISupportCodeLibrary`

src/support_code_library_builder/sourced_parameter_type_registry.ts
The `ParameterType` type is properly exported by the `cucumber-expressions` module so no need to directly reference the file.
Without this change tsc fails for me with the following error:
```
node_modules/@cucumber/cucumber/lib/support_code_library_builder/sourced_parameter_type_registry.d.ts:2:27 - error TS2307: Cannot find module '@cucumber/cucumber-expressions/dist/cjs/src/ParameterType' or its corresponding type declarations.
2 import ParameterType from '@cucumber/cucumber-expressions/dist/cjs/src/ParameterType';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in node_modules/@cucumber/cucumber/lib/support_code_library_builder/sourced_parameter_type_registry.d.ts:2
```
----
*This text was originally …
=> Fix type import from cucumber-expressions

.mocharc.yml, compatibility/cck_spec.ts, compatibility/features/attachments/attachments.ts, compatibility/features/hooks/hooks.ts, compatibility/features/parameter-types/parameter-types.ts, compatibility/features/pending/pending.ts, compatibility/features/rules/rules.ts, compatibility/features/skipped/skipped.ts, compatibility/features/undefined/undefined.ts, package-lock.json, package.json
Update all the `@cucumber/*` packages to latest versions.
Fix the CCK - this was unwittingly broken when we upgraded `glob` and was running 0 tests as a result - changed the mocha config so this will be caught if it happens again.
Removed `stream-buffers` dependency which we no longer need after the CCK changes.
Incorporate recent CCK changes.
----
=> chore: update cucumber packages and fix CCK

.github/workflows/build.yaml, CHANGELOG.md, package-lock.json, package.json
Start validating on Node.js 21, the current version.
----
=> Add official support for Node.js 21
