- README.md
Some file names in the documentation use snake_case, others camelCase. This PR uses snake_case consistently for filenames, which is a generally recommended best practice for file names since some file systems are case sensitive (Linux) while others are not (OS X).
> Avoid file names with uppercase characters

- features/step_definition_snippets.feature
- lib/cucumber/listener/summary_formatter.js
As mentioned in #554, here is my update with the additional scenario to check for a missing step definition in the background section of a feature file.  I have also included my dodgy fix, but will not be in any way offended if it's not used! :)
> added test scenario for missing background step definition

- lib/cucumber/listener/json_formatter.js
- package.json
- spec/cucumber/listener/json_formatter_spec.js
this removes the `base-64` dependency which doesn't support binary input (it throws an error if input is not ASCII), that makes json formatter fail if any attachment is binary (like screenshots are), replacing it node.js native base64 encoding.
as a side benefit, native encoding is probably (not measure) faster, and it's one less dependency to care about.
> native base64 encoding, fix for binary attachments

- lib/cucumber/runtime/stack_trace_filter.js
When an asynchronous test step returns a promise rejected with an `Error` (`AssertionError` in the case of Chai), such as:
```javascript
return expect(browser.getTitle()).to.eventually.equal('my website')
```
Cucumber produces the following error output:
```
/Users/jan/project/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:9
var fileName = frame.getFileName() || '';
^
TypeError: node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:60 Cannot read property 'getFileName' of undefined
at isFrameInCucumber (/Users/jan/project/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:9:23)
at Array.<anonymous> (/Users/jan/project/node_modules/cucumber/lib/cucumber/runtime/stack_trace_filter.js:15:9)
at TraceModifier._modify …
```
> stack_trace_filter no longer blows up when given an error object without a stack trace

- features/multiple_formatters.feature
- features/pretty_formatter.feature
- features/profiles.feature
- features/rerun_formatter.feature
- features/target_specific_scenarios_by_line.feature
- features/target_specific_scenarios_by_tag.feature
- lib/cucumber/listener/pretty_formatter.js
- package.json
- spec/cucumber/listener/pretty_formatter_spec.js
@charlierudolph 
Some Windows shells only support a limited character set. Using [figures](https://github.com/sindresorhus/figures) makes the new unicode output of Cucumber more compatible across all platforms.
> Use cross-platform symbols

- docs/support_files/event_handlers.md
Hi,
Was trying to use the event handlers in cucumber but the links didn't work after the documentation refactor. Procrastinating made this pull request for you.
Hope it helps.
Oli
> Change links in event_handlers.md docs to make navigation work

- features/rerun_formatter.feature
- features/step_definitions/file_steps.js
- features/step_definitions/json_output_steps.js
- lib/cucumber/cli/configuration.js
Fixes #657. This prevents all the tests from running when there is a trailing newline in the rerun file.
> Trim paths from @rerun files

- CHANGELOG.md
In old Cucumbers, multiple `--tags` is conjunction (and), comma-separated tags is disjunction (or).
> Fix tag expression migration guide

- docs/cli.md
`format-option` without trailing `s` is not recognized.
> Fix CLI format-options name

- CHANGELOG.md
- docs/support_files/api_reference.md
- docs/support_files/attachments.md
- docs/support_files/hooks.md
- docs/support_files/timeouts.md
- docs/support_files/world.md
[MacDown](http://macdown.uranusjr.com), my favorite local markdown reader for *OSX* doesn't handle well block of code if not precedeed by an empty line. This PR fix that and uniform `'''js` to `'''javascript`
> Fix documentation for some markdown parser

- features/hooks.feature
- features/step_definitions/cli_steps.js
- features/step_definitions/json_output_steps.js
- lib/cucumber/runtime/event_broadcaster.js
This PR resolves https://github.com/cucumber/cucumber-js/issues/792.
Currently returning a rejected promise from the BeforeFeatures hook will cause the run to:
- Exit with code=0 (expected=1).
- Throw a node unhandled rejection error.
> Resolve unhandled rejection in BeforeFeatures hook #797

- features/global_install.feature
- features/step_definitions/cli_steps.js
- features/support/hooks.js
- features/support/world.js
- package.json
- src/cli/install_validator.js
- src/cli/run.js
- yarn.lock
> error when running a global install

- .gitattributes
Force lf line endings for all js files. This is useful for windows users that configured their line-endings as `auto`.
> chore: Force lf line endings for js files

- features/step_wrapper_with_options.feature
- src/support_code_library/builder.js
It would be helpful to have the options available in the wrapper.
Then I can do something like this:
```javascript
defineSupportCode(function ({setDefinitionFunctionWrapper}) {
setDefinitionFunctionWrapper(function (fn, options) {
let retryTest = isFinite(options.retry) ? parseInt(options.retry, 10) : 0
let wrappedFunction = isAsync(fn) || config.sync === false
? wrapStepAsync(fn, retryTest) : wrapStepSync(fn, retryTest)
return wrappedFunction
})
})
```
I'm currently writing a "wdio-cucumber2-framework" (which is a wrapper around cucumber 2 to allow webdriverio runner run cucumber tests), and this is the cleanest way for me to implement retrying (this is how it was done in wdio-cucumber-framework as well , with the options)
Please let me know what you think, I hope you don't feel like …
> pass the step definition options to function wrapper

- docs/support_files/step_definitions.md
I got tripped up when looking at these examples that [node's assert](https://nodejs.org/api/assert.html) needs to be imported explicitly to be used
> Update step_definitions.md- explicit assert import

- features/i18n.feature
- package.json
- src/cli/argv_parser.js
- src/cli/configuration_builder.js
- src/cli/configuration_builder_spec.js
- src/cli/i18n.js
- src/cli/index.js
- yarn.lock
resolves #763
@mattwynne @danascheider I cleaned up the output and use different cli options then ruby in case you are interested.
> add i18n command line options

- src/formatter/json_formatter.js
- src/formatter/json_formatter_spec.js
Hello,
I want to use jenkins to generate report from json file generated by JsonFormatter. We're using https://github.com/jenkinsci/cucumber-reports-plugin to generate cucumber reports on jenkins, but to do that "type" tag for scenario is required to identify element as scenario.
> Type tag with 'scenario' as value added to scenario element

- features/before_after_all_hook_timeouts.feature
This is tiny change on top of #899: pluralize a word in the Scenario Outline to make it fit the grammar of the sentence.
> Scenario Outline name rename: pluralize word

- features/formatter_paths.feature
- features/step_definitions/cli_steps.js
- features/step_definitions/file_steps.js
- package.json
- src/cli/index.js
- yarn.lock
I needed this fix to get protractor support for cucumber 3.
- Moved the invalid path scenario that was in `multiple_formattters.feature` to a new `formatter_paths.feature` so all the path related scenarios were together.
- Added mustache to get the temp dir into the feature. ~~Added a new `replaceContextVariables` helper so that I could get the actual temp dir into the feature itself. It felt kind of hacky, but I didn't know of another way besides duplicating step definitions to deal with absolute paths explicitly.~~
> Allow absolute formatter output paths. Fixes #900.

- CHANGELOG.md
CHANGELOG.md updates as per [cucumber/cucumber #251](https://github.com/cucumber/cucumber/issues/251)
I've run my [changelog_updater](https://github.com/jaysonesmith/changelog_updater) and have gone through to fix other nuanced items, mainly ordering of issue tags and credit tags in a single set of parens after the changed line.
> CHANGELOG Update for cucumber/cucumber #251

- docs/support_files/api_reference.md
- docs/support_files/attachments.md
- docs/support_files/hooks.md
- features/attachments.feature
- features/hook_parameter.feature
- package.json
- src/models/test_case_hook_definition.js
- src/runtime/step_runner.js
- src/runtime/test_case_runner.js
- src/status.js
- src/status_spec.js
- yarn.lock
> fix undefined hook parameter

- src/formatter/helpers/usage_helpers/index.js
- src/formatter/helpers/usage_helpers/index_spec.js
- src/formatter/usage_formatter_spec.js
Currently was running into this error if there was an undefined step:
```
TypeError: Cannot read property 'uri' of undefined
at formatLocation (/Users/charlesrudolph/projects/cucumber-js/src/formatter/helpers/location_helpers.js:2:13)
at /Users/charlesrudolph/projects/cucumber-js/src/formatter/helpers/usage_helpers/index.js:29:26
at Array.forEach (native)
at /Users/charlesrudolph/projects/cucumber-js/src/formatter/helpers/usage_helpers/index.js:26:20
at /Users/charlesrudolph/projects/cucumber-js/node_modules/lodash/lodash.js:4944:15
at baseForOwn (/Users/charlesrudolph/projects/cucumber-js/node_modules/lodash/lodash.js:3001:24)
at /Users/charlesrudolph/projects/cucumber-js/node_modules/lodash/lodash.js:4913:18
at Function.forEach …
```
> fix usage helpers

- docs/cli.md
- src/formatter/rerun_formatter.js
- src/formatter/rerun_formatter_spec.js
Allows to change the separator in the rerun formatter, eg. `--format-options '{ separator: " " }'`. This way you can get the list of failing tests in a single line that could be handy sometimes.
> Custom separator support for rerun formatter

- docs/cli.md
- features/target_specific_scenarios_by_tag.feature
- src/cli/argv_parser.js
> Support repeatable tags option

- docs/support_files/api_reference.md
- features/parameter_types.feature
- package.json
- src/models/step_definition.js
- src/runtime/step_runner.js
- yarn.lock
Allow `transformer` functions to delegate to World
Because sometimes we need stuff from the world to transform a string to a "rich" object
Unit tests in cucumber-expressions, new scenario in this PR
> ParameterType transformer runs in World

- docs/support_files/api_reference.md
- features/hook_parameter.feature
- src/runtime/test_case_runner.js
Resolves these issues: 
[Result is missing scenario & tags](https://github.com/cucumber/cucumber-js/issues/923)
[testCase does not contain Scenario name ](https://github.com/cucumber/cucumber-js/issues/943)
resolves #923
> (refactor) Update testCase to include pickle object

- src/cli/configuration_builder.js
- src/cli/configuration_builder_spec.js
That regex feels hacky to me so if there is a way to do this with a single `split` without checking the number of split parts I'd be more than happy to use it. It's still splitting on a `:`, but not if it is preceded by a capital letter and followed by a `/` (at least that was my intention). I looked at [this old pr](https://github.com/cucumber/cucumber-js/pull/680/files#diff-125eabbcc2e8302c4674fbbcc2fa3439R106), but couldn't tell if that would work in this situation. Regex hurts my head.
> cli: don't split formatter:output on Windows drive letters (#953)

- src/pickle_filter.js
- src/pickle_filter_spec.js
resolves [#924](https://github.com/cucumber/cucumber-js/issues/924)
> pickle_filter: use absolute paths

- src/cli/configuration_builder.js
- src/cli/option_splitter.js
- src/cli/option_splitter_spec.js
Thought I'd take a crack at #746 while I was dealing with `:` splitting for the formatters. The compiler isn't as easy to unit test as the formatters was since the result of the split is used internally to the config builder plus it actually `require`s the module so you can't just send anything you want to it...like a windows absolute path. So I added an `OptionSplitter` utility that both the `--format` and `--compiler` can use. There are no new tests for `--compiler` because of the reason above, but the existing [feature](https://github.com/cucumber/cucumber-js/blob/master/features/compiler.feature) should ensure there are no regressions.
The splitting itself almost turned out to be simple with negative look aheads and look behinds until I found out that js regex doesn't support look …
> cli: extract option splitting and use it for --compiler (#746)

- package.json
- src/formatter/json_formatter.js
- yarn.lock
Add exception.message to error_message if not already included in exception.stack
Fix #957
> Exception message in json formatter

- features/attachments.feature
- features/step_definitions/json_output_steps.js
- src/formatter/json_formatter.js
- src/formatter/json_formatter_spec.js
> revert json formatter

- features/before_after_all_hook_timeouts.feature
- features/hook_timeouts.feature
- features/step_definition_timeouts.feature
- src/user_code_runner.js
- src/user_code_runner_spec.js
https://github.com/cucumber/cucumber-js/issues/1019
> vary error for callback vs promise

- docs/support_files/attachments.md
- features/error_formatting.feature
- src/formatter/helpers/issue_helpers.js
- src/formatter/helpers/issue_helpers_spec.js
I found hard to log information right after a step without rewriting a whole custom formatter.
I suggest formatting each step attachment (text only) as line in the error summary.
What do you think ?
> Print attachment step text on error format

- docs/cli.md
add quotes around --require args to prevent shell expansion. #1040
> Update cli.md: ## Transpilers

- CHANGELOG.md
It took me a while to figure out why the console was still printing colors even though I disabled them through "--format-options", but I figured out that's because "false" is parsed as true if used as string in JSON. Correct usage: --format-options '{"colorsEnabled": false}'
> Removed double quotes for JSON boolean value

- package.json
- yarn.lock
Helps with resolving https://github.com/cucumber/cucumber-js/issues/1124, builds on top of https://github.com/medikoo/duration/issues/5. This is really just optional as the current version in both `package.json` and the lock file contain `^`, so for everyone `duration` should upgrade automatically.
> Upgrade duration

- features/skipped_steps.feature
- src/runtime/test_case_runner.js
If I skip a Scenario from a Before hook (like explained [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#skipping-in-a-before-hook)) but I also add an After hook, the execution of the After hook causes the status of the scenario to change from `SKIPPED` to `PASSED`
To see the issue on the [browser example](http://cucumber.github.io/cucumber-js/), paste the following code in the steps definitions
<details><summary>Step definitions</summary>
<p>
```javascript
// Cucumber and chai have been loaded in the browser
var setWorldConstructor = Cucumber.setWorldConstructor;
var Given = Cucumber.Given;
var When = Cucumber.When;
var Then = Cucumber.Then;
var Before = Cucumber.Before;
var After = Cucumber.After;
var expect = chai.expect;
///// World /////
//
// …
```
> Keep skipped status

- features/parallel.feature
- src/runtime/parallel/master.js
- src/runtime/parallel/run_slave.js
- src/runtime/parallel/slave.js
When running in parallel mode, if the `BeforeAll` hook fails it throws an error that nothing is currently catching, resulting in an unhandled rejection error and the slave hanging forever.
I've updated the files involved to console.error log the message and exit the process with an error code (this is what the non parallel run does (https://github.com/cucumber/cucumber-js/blob/master/src/cli/run.js#L5))
Also needed to update master and slave runner to use the process error code to fail the test.
> handle hook errors in parallel mode

- src/formatter/helpers/usage_helpers/index.js
- src/formatter/helpers/usage_helpers/index_spec.js
- src/support_code_library_builder/finalize_helpers.js
- src/support_code_library_builder/index_spec.js
When interrogating the `supportCodeLibrary` for producing a usage formatter or (in my case) documentation for all your steps, there is the `code` property on each `stepDefinition`, the value of which is the actual function you passed to `defineStep` or one of its aliases. This can then be printed, or run through a parser, etc.
However, if you use `setDefinitionFunctionWrapper`, that `code` is replaced by the generated wrapper function, which being just a delegate is not much use to look at or parse.
With this change, when applying a definition function wrapper, we preserve the original function on a new property `unwrappedCode` so it can be referenced if needed. I also updated the usage helper to reflect this.
> set original code on `unwrappedCode` if wrapping

- features/retry.feature
- src/runtime/test_case_runner.js
- src/runtime/test_case_runner_spec.js
Fixes #1248 
Moved the creation of the World into the method that resets the state before each attempt. In doing so, needed to turn a couple of local variables from the constructor into instance fields.
> create a fresh World instance for every retry

- src/formatter/json_formatter.js
- src/formatter/json_formatter_spec.js
The duration (which was already in nanoseconds) was being multiplied by 1000000 in src/formatter/json_formatter.js. This lead to the duration being reported in femtoseconds instead of nanoseconds, as it was in Cucumber 5.x. I'm not sure why this addition was added, but, this PR fixes the behaviour and returns the duration to the previously correct value.
EDIT: as noted below, this error was introduced in 6.0.0, which changed the internal reporting from milliseconds to nanoseconds. The JSON formatter was not updated when the change happened.
Fixes #1256
> #1256 Fix duration being multiplied by 1000000 in JSON reporter

- package.json
- yarn.lock
Resolves the security alert for https://github.com/cucumber/cucumber-js/network/alert/yarn.lock/handlebars/open as that was a nested dependency of it but in newer versions no longer is
> update dependency: nyc

- docs/cli.md
Remove reference to `event-protocol` formatter and instead mention `message` formatter with a link to the messages library.
> docs: update built-in formatters after cucumber-messages migration

- features/dryrun_mode.feature
- src/runtime/index.ts
- src/runtime/parallel/command_types.ts
- src/runtime/parallel/master.ts
- src/runtime/parallel/slave.ts
> runtime: don't execute BeforeAll and AfterAll hooks when in dry-run

- README.md
We now have various unreleased breaking changes on master, including the move to cucumber-messages, so adding a link to the 6.x branch (created from 6.0.5 tag) so we can point people at docs representing the current released version.﻿
> docs: add link to 6.x branch for documentation

- bin/run_slave
- package.json
- src/runtime/parallel/master.ts
- src/runtime/parallel/run_slave.ts
- src/time.ts
Don't need run_slave in bin since we are using fork where we pass the path to a node file.
While testing out parallel, also noticed some the parallel reported time was broken. No tests for those as we should switch to using some from cucumber-messages soon
> cleanup run slave + fix parallel time

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package.json
I noticed that the demo site is linked without https and doesn't have a redirect in place. That seemed worth fixing.
I went through the rest of the project looking for other links that could be improved:
* to add https
* where the ultimate site was different (e.g. paths changed or needed a www subdomain)
* where the websites were no longer responding:
* jbpros.net is offline
* simondean.org is a placeholder cpanel page
The last 2 items are the most worth attention, I think.
> Using https where possible. Removing offline sites.

- package.json
Missed this when I removed Node 8 support previously.
> build: define node support as 10+ in package.json

- CHANGELOG.md
- src/support_code_library_builder/build_helpers.ts
- src/support_code_library_builder/types.ts
Since we are building up to a major release - this was [deprecated](https://github.com/cucumber/cucumber-js/pull/904) back in 2017.
> remove typeName from options object for defineParameterType

- CHANGELOG.md
- package.json
- yarn.lock
Hi ! :wave: 
Advisory : https://www.npmjs.com/advisories/1523
I don't know why renovate didn't update that one yet.
> chore(deps): bump lodash from 4.17.16 to 4.17.19

- docs/nodejs_example.md
Using `expect` from the `chai` package` in Cucumber documentation creates the misleading perception that Cucumber-JS requires or recommends chai in any way. At the very least, it requires people who don't know chai to learn about it. Node now provides a [built-in assertion library](https://nodejs.org/api/assert.html). How do you feel about using it in the Cucumber documentation?
> Use Node's built-in assertion library in example

- CHANGELOG.md
Not sure if we should call out any differences between `@types/cucumber` and our own typings. For example `TableDefinition` -> `DataTable`.
I started looking at using [tsd](https://github.com/SamVerschueren/tsd) to test the example code from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cucumber) to expose the differences, going to continue with that today.
Fixes #1269
> docs: add changelog note about typescript

- src/formatter/helpers/summary_helpers.ts
- src/formatter/helpers/summary_helpers_spec.ts
- src/formatter/progress_bar_formatter.ts
- src/formatter/summary_formatter.ts
- src/runtime/index.ts
- src/runtime/parallel/coordinator.ts
- src/runtime/pickle_runner_spec.ts
- src/runtime/stopwatch.ts
- src/runtime/stopwatch_spec.ts
- src/time.ts
This fixes a few bugs with time/duration handling
* The timestamp of testRunStarted was 0. It's been fixed to be an actual timestamp (Date.now).
* The timestamp of testRunFinshed was not a timestamp, but a duration camouflaged as a timestamp.
* The stopwatch.timestamp() method no longer calculates the timestamp from a duration (which is impossible). Instead it uses Date.now()
* Previously the reports test run duration was based on the testRunFinshed timestamp alone, which didn't make sense. A timestamp is not a duration. Instead we calculate it using the difference of the testRunStarted and testRunFinished timestamps
We think there is still some work to do to clean up the timestamp/duration code, but this should be done in a separate PR. This PR simply focuses on getting correct values …
> Compute timestamp Using Date.now (without deriving from duration)

- features/publish.feature
- features/step_definitions/cli_steps.ts
- features/support/world.ts
Recently had failing tests related to getting a 401 from the reports server.
https://travis-ci.org/github/cucumber/cucumber-js/jobs/737307595
Updated our feature tests to always use the stubbed reports server.
> publish features use stubbed reports server

- src/runtime/index.ts
- src/runtime/pickle_runner.ts
- src/runtime/pickle_runner_spec.ts
removes the internal concept of a `pickleRunner` result. This is outdated and based on when a testCase had a result and now we only report testStep results and use the `getWorstTestStepResult` from cucumber query.
Idea for the refactor came out of reviewing #1416 where `pickleRunner.result` was being used in the wrong way.
> cleanup pickle runner

- CHANGELOG.md
- features/support/world.ts
- package.json
- src/formatter/builder.ts
- tsconfig.json
- yarn.lock
This commit makes it possible to load a custom formatter that is not relative to the current working directory, such as one installed
globally, or via Yarn PNP. This change makes it so we only load by a relative path if it begins with a dot, otherwise it will load
it as a regular non-relative require.
Fixes #1412
> Load custom formatter by relative path only if it begins with a dot

- .nycrc
- scripts/test-coverage.sh
I broke this when adding CCK.
- Exclude CCK support code from metrics
- Add missing `--no-clean` so we aren't losing data from the unit test run
> build: fix coverage reporting

- docs/cli.md
- note that it supports multiple usage
- make clear that defaults are not applied once you specify with the option
Closes #1460
> docs: add clarity to docs on `--require`

- .travis.yml
Fixes #1444 
The [`yarn audit`](https://classic.yarnpkg.com/en/docs/cli/audit/) command checks (via the npm registry's audit service) for security vulnerabilities in dependencies (including transitive) and exits with a non-zero if any are found. It's checking the same database [as dependabot does](https://dependabot.com/blog/securing-javascript-transitive-dependencies/) and is also easy to do locally by running the same command.
This should mean we get a flow of:
1. Vulnerability is made public
2. Builds from `master` start to fail
3. Dependabot raises a PR, and its build passes
By default any and all issues will fail the build. We can specify a [severity level](https://docs.npmjs.com/about-audit-reports#severity) at which it starts failing if we want - open question as to whether we …
> build: add yarn audit to ci

- docs/nodejs_example.md
As the 'cucumber' package is obsolete I propose the change to '@cucumber/cucumber' in install script to version 7.0.0.
> Using @cucumber/cucumber instead cucumber

- CHANGELOG.md
- README.md
- docs/cli.md
- docs/custom_formatters.md
- docs/faq.md
- docs/migration.md
- docs/support_files/api_reference.md
- docs/support_files/attachments.md
- docs/support_files/hooks.md
- docs/support_files/step_definitions.md
- docs/support_files/timeouts.md
- docs/support_files/world.md
- Add a dedicated migration guide, link to it from main readme and changelog
- Update formatter docs to be more readable and specify different flavours of formatter descriptor (fixes #1517)
- Update docs on parallel now that we fixed the timing in the summary formatter
- Add advice for distribution of custom formatters
- Modernise the documentation around `World` (fixes #1520)
- Fix the package name in documentation examples
- Remove reference to built-in pretty formatter (fixes #1546)
- Document a common issue (and workaround) from npm linking step libraries (fixes #1326)
> docs: migration guide and other documentation improvements

- CHANGELOG.md
- docs/support_files/attachments.md
- features/attachments.feature
- src/runtime/attachment_manager/index.ts
- src/runtime/attachment_manager/index_spec.ts
Fixes #1550.
After the refactor to accomodate messages, we made it impossible to attach content that was already base64 encoded, since passing a string and mime type to the `attach` function will cause it to be set as "identity".
This makes it possible via a prefix on the mime type parameter e.g. `base64:image/png`. I'm not particularly wedded to this solution but it seems reasonable. Things we could do instead:
- Add a third parameter to the `attach` function
- Add an alternate function e.g. `this.attachBase64`
- Auto-detect internally - possible but a lot of wasted computation as we'd need to base64 decode and then encode each string to understand if it started out base64 encoded or not
> attachments: support attaching already-encoded base64 content

- tsconfig.json
We were already emitting source maps, but Node was unable to really use them at runtime because we don't also include the TypeScript source files in the package. Doing that feels a bit off to me - could lead to issues with end users trying to use the source files directly with their own tsconfig. This change means we inline the source content with the source map files, so stack traces and debuggers can do their thing.
> build: inline sources in source maps

- docs/cli.md
- features/retry.feature
As raised on Slack:
> Can the `--retry` and `--fail-fast` flags be used together to get the test to fail if a scenario runs out of retries?
We didn't have this covered or documented, so wanted to test the behaviour and check if it matches intent. I think it's right - we consider a test case to have failed if it exhausts retries and still fails, but passed if it passes on a retry having failed previous attempts, so `--fail-fast` still allows retries to happen.
> add examples to prove retry and fail fast interplay

- .github/workflows/build.yml
- CHANGELOG.md
- cucumber.js
- features/publish.feature
- features/step_definitions/cli_steps.ts
- features/support/hooks.ts
- package.json
- src/cli/index.ts
- src/formatter/http_stream.ts
- src/formatter/http_stream_spec.ts
- test/fake_report_server.ts
Other Cucumber implementations display the content send by the server upon failure. For example, with Cucumber ruby:
```
$ CUCUMBER_PUBLISH_TOKEN=plop bundle exec cucumber features/docs/getting_started.feature
WARNING: Nokogiri was built against LibXML version 2.9.10, but has dynamically loaded 2.9.4
Using the default profile...
........
2 scenarios (2 passed)
8 steps (8 passed)
0m0.023s
┌──────────────────────────────────────────────────────────────┐
│ Invalid CUCUMBER_PUBLISH_TOKEN: plop                         │
│ Go to https://reports.cucumber.io/profile to get your token. │
└──────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
1: from /Users/vincent.pretre/dev/open-source/cucumber-ruby-meta/cucumber-ruby/lib/cucumber/formatter/io.rb:40:in …
```
> Display error banner when Reports server returns status code ≠ 2xx

- CHANGELOG.md
- docs/cli.md
- src/formatter/json_formatter.ts
Closes #1250 as agreed in today's community call for all implementations.
The previous deprecation has resulted in some hesitation to upgrade from users who use tools that rely on the JSON formatter output.
The tone now is about "maintenance mode" - it'll stay functional, but won't benefit from any new features. As the documentation and tooling around messages improves, we'll gradually encourage authors of maintained tools to switch over to that. Feedback welcome on the exact wording. Also, the noisy console warning is gone.
> cli: undeprecate json formatter

- CHANGELOG.md
- features/scenario_outlines.feature
- src/formatter/json_formatter.ts
- src/formatter/json_formatter_spec.ts
- test/fixtures/json_formatter_steps.ts
> Fix #1621: Json formatter fails with tagged examples

- docs/cli.md
- docs/migration.md
Last piece of #1532.
We need TypeScript users to have this on due to an upstream library that exports typings doing an `import` of a JSON file. I think this is very common and it seems more sensible to advise users to switch the compiler option on than try to control what goes on in libraries.
> docs: add note about resolveJsonModule for TS

- src/cli/profile_loader.ts
- src/formatter/helpers/event_data_collector.ts
- src/formatter/helpers/gherkin_document_parser.ts
- src/formatter/helpers/issue_helpers.ts
- src/formatter/helpers/pickle_parser.ts
- src/formatter/helpers/test_case_attempt_parser.ts
- src/formatter/helpers/usage_helpers/index.ts
- src/formatter/json_formatter.ts
- src/models/data_table.ts
- src/pickle_filter.ts
- src/runtime/parallel/coordinator.ts
- src/support_code_library_builder/validate_arguments.ts
Helps with #1532 - avoids an implicit dependency on `@types/lodash` where TypeScript users reference some of our models and functions.
> replace use of Dictionary with Record

- CHANGELOG.md
- src/cli/helpers.ts
- src/cli/index.ts
- src/formatter/helpers/issue_helpers_spec.ts
- src/formatter/helpers/test_case_attempt_parser.ts
- src/formatter/helpers/usage_helpers/index.ts
- src/formatter/json_formatter.ts
- src/formatter/rerun_formatter.ts
- src/pickle_filter.ts
- src/pickle_filter_spec.ts
> cli: have gherkin emit uris relative to the cwd

- src/index.ts
- src/support_code_library_builder/types.ts
- test-d/hooks.ts
Much of the list from https://github.com/cucumber/cucumber-js/issues/1646#issue-863352190. Most of the rest already available under formatter helpers, probably just need some manual editing in those projects.
> debt: add things to main entry point that people need

- README.md
- docs/cli.md
- docs/parallel.md
- docs/profiles.md
- docs/retry.md
- docs/support_files/world.md
Problems:
- The CLI page is very long and not easy to find information in.
- Many useful features are only mentioned briefly.
- Some closely-related topics aren't documented together (e.g. `World` and `--world-parameters`)
- We don't really have a "Getting Started" guide
This series of PRs aims to split out most of the content from the CLI page into targeted articles with examples and add a "Getting Started" guide. [AVA](https://github.com/avajs/ava) is one project that does this well (see "Recipes" in their README).
Other articles to add:
- Rerun
- Formatters
- Snippets
- TypeScript
- Markdown
- Assertions
- Browser Automation
I'd also like to refresh the README (see #1521) but that can be done separately.
> refactor documentation (part 1)

- CHANGELOG.md
- features/publish.feature
- src/cli/publish_banner.ts
Also see https://github.com/cucumber/docs/pull/636
> Fixed reports banner to point to https://cucumber.io/docs/cucumber/environment-variables/

- docs/faq.md
- docs/support_files/api_reference.md
- docs/support_files/hooks.md
- docs/support_files/step_definitions.md
- docs/support_files/world.md
Some users use arrow functions without realising that they cannot access the world from them.
This is currently described in the FAQ, but people still miss it. I've therefore added more sign-posts from the hook, step definition and parameter type docs.
I also tweaked the FAQ entry a little.
> Add more arrow function warnings

- CHANGELOG.md
- features/target_specific_scenarios_by_line.feature
- src/cli/configuration_builder.ts
- src/cli/configuration_builder_spec.ts
Fix the issue where the same scenarios are executed multiple times when the feature file is targeted multiple times.
Example:
```shell
$ npx cucumber-js features/simple_math.feature:19 features/simple_math.feature:20
```
Will now result in:
```
...
2 scenario (2 passed)
6 steps (6 passed)
```
Fixes #1706
> fix(cli): allow targetting same file multiple times

- CHANGELOG.md
- features/retry.feature
- src/cli/argv_parser.ts
- src/cli/configuration_builder.ts
Remove the camelCase version of this CLI option as deprecated in 7.0.0 via https://github.com/cucumber/cucumber-js/pull/1293.
- Breaking change (will cause existing functionality to not
work as expected)
> cli: remove deprecated retryTagFilter option

- CHANGELOG.md
- src/support_code_library_builder/index.ts
Emit a warning when you call `setDefinitionFunctionWrapper`, using same wording as the removal notice in #1725.
Give users a bit of warning about the removal in 8.0.0.
Then going to release as 7.3.1 (we had another couple fixes ready anyway on 7.x).
> docs: officially deprecate setDefinitionFunctionWrapper

- CHANGELOG.md
- src/formatter/get_color_fns.ts
bringing back v6/5 `get_color_fns` props
Fixes #1582
- Bug fix (non-breaking change which fixes an issue)
> bringing back v6/5 props

- CONTRIBUTING.md
As mentioned in the new contributors ensemble [retro]
[retro]: https://github.com/cucumber/cucumber-js/blob/main/docs/retro/2021/07/17.md#what-should-we-decide--change-for-next-time
> Tweak CONTRIBUTING guide to be more beginner-friendly

- CHANGELOG.md
- CONTRIBUTING.md
- features/support/hooks.ts
- features/support/warn_user_about_enabling_developer_mode.ts
- package-lock.json
- package.json
* Add a try/catch block around a line in our `features/support` code that creates a symlink. If you're using Windows, unless you have enabled "Developer Mode" this line throws an error. We now catch the error and show a helpful message to the user.
* Replace uses of `cp` command (which is not available in a Windows PowerShell / `cmd.exe` prompt) with an equivalent `npx` command that will work cross-platform. 
* The features won't run if you don't have "Developer Mode" enabled. See #1852
* The `build-local` script won't run unless you have a `cp` command in your path.
Big thanks to @RukenaG for inspiring this change!
> Smoother onboarding for Windows developers

- .gitignore
- CHANGELOG.md
- features/step_definitions/cli_steps.ts
- package-lock.json
- package.json
- src/cli/argv_parser.ts
- src/cli/helpers.ts
- src/index.ts
Fixes. #1853 
With ESM support, the version number of cucumber-js is not as exposed as it was due to package.json not exported.
It seems more reliable with ESM to have version defined in a source file then exported by the libraries.
To keep the version sync with the one defined in package.json, the npm package [genversion](https://www.npmjs.com/package/genversion) has been used.
Pretty sure it may be useful with the incoming API too :)
I think we could consider this a breaking change: the way to find the version of cucumber programmatically has changed
- Breaking change (will cause existing functionality to not
work as expected)
> Export version number of cucumber-js

- CHANGELOG.md
- features/direct_imports.feature
- package.json
> Add package.json to node module exports

- features/step_definitions/cli_steps.ts
I'm continuing the process of replacing regex with cucumber expressions
It's one step towards fixing the issue #1871 
> Replace 2 instances of regex with cucumber expression

- .eslintrc.yml
- .prettierrc
Use a more conventional place to store prettier config
So that VSCode's prettier plugin can automatically find it.
Currently, VSCode doesn't understand our prettier config, so the code formatter from the prettier plugin reformats the code using defaults (e.g. adding semi-colons), which then breaks the eslint rules!
> Extract prettier config from eslintrc

- compatibility/cck_spec.ts
- compatibility/features/data-tables/data-tables.ts
- compatibility/features/examples-tables/examples-tables.ts
- compatibility/features/unknown-parameter-type/unknown-parameter-type.ts
Change uses of `any` type to use specific types.
See #1648
> Replace uses of `any` type

- .github/workflows/release-npm-latest.yaml
- .github/workflows/release-npm-next.yaml
Creates two versions of the npm release workflow - one for stable releases, and one for release candidates, based on branch naming patterns. The former are tagged as `latest` and the latter as `next`.
Unless a tag is specified, npm packages default to `latest` on publication. This meant that, when a release candidate was out, in practise users would run `npm install @cucumber/cucumber` and get the release candidate when we would want them to get the latest stable version unless they opt in to the RC.
`next` is a loose convention in the npm ecosystem for tagging prereleases. So next time there is an RC, regular users will still get the latest stable version when they install, and enthusiasts can do `npm install @cucumber/cucumber@next` to get the RC.
- Refactoring/debt (improvement to code …
> build: tag as next when publishing release candidates

- .eslintrc.yml
- compatibility/features/parameter-types/parameter-types.ts
- src/cli/helpers.ts
- src/cli/helpers_spec.ts
- src/formatter/get_color_fns.ts
- src/formatter/helpers/issue_helpers.ts
- src/formatter/helpers/issue_helpers_spec.ts
- src/formatter/helpers/summary_helpers_spec.ts
- src/formatter/helpers/test_case_attempt_formatter.ts
- src/formatter/helpers/test_case_attempt_parser.ts
- src/formatter/helpers/test_case_attempt_parser_spec.ts
- src/formatter/helpers/usage_helpers/index.ts
- src/formatter/helpers/usage_helpers/index_spec.ts
- src/formatter/progress_bar_formatter.ts
- src/formatter/progress_bar_formatter_spec.ts
- src/formatter/snippets_formatter.ts
- src/formatter/summary_formatter.ts
- src/formatter/usage_formatter.ts
- src/formatter/usage_json_formatter.ts
- src/run/runCucumber.ts
- src/runtime/parallel/coordinator.ts
This rule got turned off during a lint upgrade and think its useful to have on
> lint: error on unused vars

- src/cli/assert_node_engine_version.ts
- src/cli/assert_node_engine_version_spec.ts
- src/cli/run.ts
Instead of having a try/catch around this function just have it return an optional error message.
> avoid throwing for flow control

- CHANGELOG.md
- features/gherkin_parse_failure.feature
- features/step_definitions/cli_steps.ts
- src/api/runCucumber.ts
- src/cli/helpers.ts
Don't throw immediately when a parse error is encountered by gherkin - instead ensure all the errors (as well as any valid sources) are emitted and do a normal cleanup and exit.
Avoided making this part of `parseGherkinMessageStream` because that's on the public API (for now) and I didn't want to make a breaking change to its signature unnecessarily.
Fixes #1404.
Previously we'd throw on the first parse error and formatters wouldn't have a chance to do anything with it before the process exited.
> run: handle parse errors better

- package.json
- src/cli/validate_node_engine_version_spec.ts
Allow any Node.js version equal or greater than 16 as well as the LTS versions 12 and 14
A bit of an oversight when we added enforcement of `engines` - we don't want to break when a new supported version of Node.js comes out that didn't exist when we released. For example Node.js 18 will be released in April and there's no reason to stop Cucumber users from using it.
> chore: handle as-yet unreleased node.js versions

- api/index.d.ts
- package-lock.json
- package.json
- test-d/api.ts
TypeScript hasn't yet released support for subpath exports. When it does (should be soon-ish), [it will look for the "type" field on each export](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#packagejson-exports-imports-and-self-referencing) to see where the types are, so we want those values to be there ready.
At the same time, _because_ TypeScript [hasn't yet released](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#beta-delta) support for subpath exports, it can't see `@cucumber/cucumber/api`, so we just need to add a physical file that points it to the type declarations in `lib`. This is just needed for the TypeScript compiler - Node.js itself will handle the resultant `require('@cucumber/cucumber/api')` fine because it understands the …
> chore: ensure typescript will see all types correctly

- CHANGELOG.md
- docs/formatters.md
- src/api/convert_configuration.ts
- src/api/convert_configuration_spec.ts
- src/configuration/option_splitter.ts
- src/configuration/option_splitter_spec.ts
- src/formatter/builder_spec.ts
As part of the ESM support, we started loading formatters and snippet syntaxes with `await import()`. Unlike `require()`, paths you pass to `import()` have to be a valid URL, and for absolute paths that means using the `file://` scheme.
This PR:
- Adds a test to prove that classes can be successfully loaded based on a `file://` URL
- Fixes some code in the configuration module in order that `file://` URLs are correctly accounted for when parsing the `--format` option (which unfortunately uses `:` as the delimiter)
- Adds a note to the documentation on formatters.
This will also be called out in the migration guide via https://github.com/cucumber/cucumber-js/pull/1962
Fixes #1920.
> fix: ensure absolute paths (as file urls) can be loaded for formatters, snippets

- CHANGELOG.md
- UPGRADING.md
- docs/esm.md
- docs/migration.md
Adds instructions on dealing with the breaking changes. Also renames and reformats the doc to `UPGRADING.md` per standard defined in <https://github.com/cucumber/.github/blob/main/RELEASING.md#major-release>.
Final bug fix [here](https://github.com/cucumber/cucumber-js/pull/1963), and then with this we are ready for 8.0.0
> docs: UPGRADING.md for 8.0.0, some tweaks and tidy up CHANGELOG.md

- docs/parallel.md
- src/index.ts
- src/wrapper.mjs
- test-d/parallel.ts
Adds `parallelCanAssignHelpers` to main entry point.
Deep requires are not going to work forever, if we want things to be usable by consumers we should explicitly export them (and then the rest is free for us to refactor).
----
> export parallelCanAssignHelpers on main entry point

- CHANGELOG.md
- features/custom_formatter.feature
- src/formatter/builder.ts
- src/formatter/builder_spec.ts
- src/formatter/fixtures/typescript.ts
Tweak the loading of custom formatters and snippet syntaxes so we try `require()` first and then try `import()` if it turns out the target file is a module (ESM).
This mirrors how we are also now loading the configuration file.
https://cucumberbdd.slack.com/archives/C6QJ6N695/p1649071066867509
An edge case arguably, but some users in the wild have formatters in their project written in TypeScript (or something else that transpiles) and take advantage of the fact that `--require-module` means their transpiler has registered by the time the formatter is loaded.
This is quite cool and something we should avoid breaking if possible. We broke it with earlier RCs because we switched to exclusively using `import()` to load custom formatters, which doesn't yet account for just-in-time transpiled …
> fix: try require first for custom formatters so transpiled ones work

- docs/configuration.md
* Added a warning banner at the top of the config docs
Help avoid confusion like https://github.com/cucumber/cucumber-js/issues/1986
Is this useful? Should we roll this out across every page?
----
> Version banner warning on docs

- CHANGELOG.md
- features/step_definition_snippets.feature
- src/formatter/step_definition_snippet_builder/javascript_snippet_syntax.ts
- src/formatter/step_definition_snippet_builder/javascript_snippet_syntax_spec.ts
When a generated cucumber expression contained a backslash (in order to escape, say, a parenthesis) the backslash would previously be treated as a noop escape in the context of a JavaScript string. Now we add another backslash to correctly escape it.
Fixes #1324.
----
> snippets: correctly escape backslashes in generated expressions

- CHANGELOG.md
- docs/support_files/world.md
- src/support_code_library_builder/world.ts
- test-d/world.ts
- Update the world documentation to cover worlds as plain functions
- Update the world documentation to cover TypeScript stuff
- Add support for generics for world parameters on world-related interfaces and classes
Fixes #1968.
----
> world: extend docs around classes and functions, support generics for parameters

- CHANGELOG.md
- dependency-lint.yml
- package-lock.json
- package.json
closes #2005
defined direct dependency to satisfy gherkin-streams peer requirement for consumers
fixes #2005 
----
> fix(message-streams): defined direct dependency to satisfy gherkin-streams peer requirement for consumers

- .github/workflows/build.yaml
- CHANGELOG.md
- package.json
Add Node.js 18 to our tested engines.
----
> add config for node 18 testing

- CHANGELOG.md
- bin/cucumber-js
Re-add the original `cucumber-js` bin file alongside the `cucumber.js` one (which was renamed from the former in https://github.com/cucumber/cucumber-js/pull/1993).
Backwards compatibility - these files should not be referenced directly, but it happens in the wild anyway.
----
> fix: readd old bin alias for backwards compat

- CHANGELOG.md
- features/support/hooks.ts
- src/support_code_library_builder/types.ts
- test-d/hooks.ts
Fix return type of step hook function to allow async, to be more accurate and prevent compile/lint errors for users.
Fixes #2037.
----
> fix return type of step hook function to allow async

- CHANGELOG.md
- src/api/index.ts
- test-d/api.ts
Export `IConfiguration` on the API entry point.
So API users can type the configuration objects they compose and pass in to the `loadConfiguration` function. I'm doing this now and it's painful without the typing.
----
> export IConfiguration interface for API users

- docs/custom_snippet_syntaxes.md
- docs/support_files/step_definitions.md
One link points to https://cucumber.io/docs/cucumber/cucumber-expressions/ which says:
> The [Cucumber Expressions Docs](https://github.com/cucumber/cucumber-expressions#readme) have been moved to GitHub. 
So I thought we could go straight to the correct link. The other link was simply 404'ing.
> Update links to cucumber expressions documentation

- CHANGELOG.md
- src/formatter/helpers/duration_helpers.ts
- src/formatter/helpers/duration_helpers_spec.ts
- src/formatter/json_formatter.ts
Ensure the nanoseconds duration in the JSON formatter is an integer.
The way we derived a single nanoseconds number from a duration object was prone to rounding errors:
```js
(1043459 / 1000000) * 1000000
// 1043458.9999999999
```
We now do it a slightly different way and `Math.floor` the result to be sure. This is consistent with what some of the helpers from messages do (and why the message formatter was not affected even though we were providing higher resolution timestamps since 8.0.0).
Fixes #2086.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can …
> fix: ensure durations are integers in json formatter

- CHANGELOG.md
- package.json
- src/api/convert_configuration.ts
- src/api/types.ts
- src/formatter/publish.ts
This PR does the following,
- defines a new interface `IPublishConfig`
- explicitly defines the possible return values to `makePublishConfig` in `src/api/convert_configuration.ts` to `IPublishConfig | false`
- updates the `publish` property in the `IRunOptionsFormats` interface in `src/api/types.ts` to reflect the newly defined `IPublishConfig` interface or `false`
The motivation for this update/change is the incremental completion of #1648 in small manageable PRs.
I imagine this will be one of multiple PRs to replace explicit `any` with a type.
- I would love feedback on this approach to removing `any` and defining an interface for `strictly typing`, is this the recommended …
> fix: Added `IPublishConfig` interface for use in `makePublishConfig`

- CHANGELOG.md
- package-lock.json
- package.json
Override dependency `ansi-regex` to ensure we get a version that fixes a security issue.
Fixes #2109.
----
> fix: add override to ensure ansi-regex is ^5.0.1

- CHANGELOG.md
- src/time.ts
This PR does the following,
- defines a new interface `IMethods` in `time.ts` extending from `GlobalTimers`
- explicitly defines the possible return values to `beginTiming` and `endTiming` in `src/time.ts`
- `void` for `beginTiming`
- `number` for `endTiming`
- updates the `methods` object to make use of `IMethods` interface 
- updates `timeoutId` to use `TimerId` instead of `NodeJS.Timeout`
- a minor fix on link from a previous related PR
The motivation for this update/change is the incremental completion of #1648 in small manageable PRs.
I imagine this will be one of multiple PRs to replace explicit `any` with a type.
- I would love feedback on this approach to removing …
> fix: add IMethods interface for use in time module functions

- CHANGELOG.md
- src/cli/index.ts
In `Cli`, default the `stderr` property of the constructor object to `process.stderr` if it's not defined - making the property effectively optional for consumers.
We introduced this property in https://github.com/cucumber/cucumber-js/pull/2137 which was effectively a breaking change for people who use the `Cli` class for framework integrations. It managed to fly under the radar until https://github.com/cucumber/cucumber-js/pull/2092/files#diff-7f71b0d311e14868f853f726912b222ac5e2aee58d985f1758d6b8f5e19c4c5c (8.5.2) where there'll be an error if it's missing. This affects `nightwatch` for example (see #2137).
This class will shortly be deprecated in favour of `runCucumber` et al, but in the meantime it should be stable.
----
*This …
> default stderr if not provided to Cli ctor

- CHANGELOG.md
- src/time.ts
Rework time interfaces to avoid using sinon types in production code.
Fixes #2141. We shouldn't have a non-dev dependency, explicit or otherwise, on a test library's types.
----
> rework time interfaces to avoid using sinon types

- CHANGELOG.md
- src/api/load_support_spec.ts
- src/api/run_cucumber_spec.ts
- src/api/support.ts
- src/api/test_helpers.ts
- src/runtime/parallel/worker.ts
Always initialise the support code library with original coordinates so it can be loaded again in child processes.
Previously, when using the API, calling `loadSupport` and using the result in `runCucumber` with the parallel option would result in a state where:
- The parent (coordinator) process has the support code loaded
- It is happy for test cases to run since it can see they have matching step definitions
- The child processes don't have the coordinates, so they don't load the support code
And this would be followed by obscure errors as noted in the linked issue.
Fixes #2196.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-re …
> fix: include original coordinates in support code library

- CHANGELOG.md
- docs/configuration.md
- features/profiles.feature
- package-lock.json
- package.json
- src/configuration/from_file.ts
- src/configuration/from_file_spec.ts
- src/configuration/locate_file.ts
Add support for YAML as a configuration file format.
We support JS and JSON; YAML is the obvious missing option.
Also as part of this, JSON configuration files are loaded with `fs.readFile` rather than `require` - this is a small non-breaking step towards moving away from `require` for everything.
----
> support YAML for config files

- CHANGELOG.md
- src/formatter/junit_formatter.ts
- src/formatter/junit_formatter_spec.ts
Added `invalidCharReplacement` option in XML Builder in XML formatter
I could not generate an XML report file via the JUnit formatter setting if the message of a failed test case contains any invalid character (Eg: `\x08`). So, in order to prevent these cases I added `invalidCharReplacement` option for XML builder as [this documentation](https://github.com/oozcitak/xmlbuilder-js/wiki/Builder-Options#settings-related-to-value-conversions).
Feel free to suggest any change or possible improvement.
> fix(junit): could not generate xml if error message has invalid character

- .github/workflows/build.yaml
- .github/workflows/release-npm-latest.yaml
- .github/workflows/release-npm-next.yaml
- CHANGELOG.md
- package.json
> chore: add node 19 to tested list and workflow

- .github/workflows/build.yaml
- .mocharc.yml
Increase mocha timeout from 2s to 5s. We don't routinely have tests timeout so this should not make the build any slower in general.
Fixes #2234. One or two API tests are doing multiple test runs and that's taking them over the 2s timeout on Windows sometimes. I expect we'll do more of this kind of test (i.e. using the `runCucumber` API) so don't want to just do it on a test by test basis.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
> fix: update mocha config to avoid test timeouts

- CHANGELOG.md
- features/gherkin_parse_failure.feature
- src/formatter/html_formatter.ts
In the `html` formatter, change when we end the `CucumberHtmlStream` that pipes to the output stream.
Previously we did this when we saw a `testRunFinished` message, which sort of makes sense. However there are other ways for a test run to end e.g. Gherkin parse failure as in the linked issue. This meant we were awaiting a stream to finish that was never going to, and this caused the process to just exit (I'm a little hazy as to exactly why, but I could reproduce it).
Now we only end the stream in the cleanup step after the test run has finished (or an error has caused us to bail out of it) and it works for both cases - covered by existing scenarios for the happy path and a new one covering the parse failure.
Fixes #2225.
---- …
> fix: end html formatter stream at appropriate time

- .github/workflows/stale.yaml
Use GitHub's recommended action to auto stale and close issues.
To begin with, just focusing on this flow for issues that we've labelled as "incomplete" (i.e. the requester hasn't provided enough information):
- After 3 weeks, mark stale and comment
- After 5 more days, close
https://github.com/cucumber/common/issues/2140
----
> chore: add workflow for closing incomplete issues

- CHANGELOG.md
- features/fixtures/formatters/passed-scenario-outline.json.ts
- features/fixtures/formatters/passed-scenario-outline.message.json.ts
- features/formatters.feature
- src/formatter/json_formatter.ts
In the JSON formatter, use the line from the _last_ referenced AST node to refer to examples from a scenario outline. In these cases there are two nodes referenced - one for the outline and one for the example.
Fixes #2223.
----
> fix: refer to example location not outline location in json formatter

- CHANGELOG.md
- src/runtime/attachment_manager/index.ts
- test-d/attachments.ts
Make the typings for `this.attach` more accurate by providing overload definitions. Also correct the `this.log` type as it can never yield a promise.
Included `tsd` test that would fail without these changes.
Fixes #2143 re the ambiguity of whether or not to expect a promise for stream attachments (depends on whether you pass in a callback), but it also improves the type safety around `mediaType` which is really only optional for string attachments.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
> make typing for attach and log functions correct

- .github/workflows/build.yaml
- package.json
12 and 17 are no longer officially supported: https://github.com/nodejs/release#release-schedule
Will need to a major release for this change. Any other incoming breaking changes planned?
> drop support for node 12/17

- features/step_definition_snippets_interfaces.feature
- src/formatter/step_definition_snippet_builder/javascript_snippet_syntax.ts
- src/formatter/step_definition_snippet_builder/javascript_snippet_syntax_spec.ts
- src/formatter/step_definition_snippet_builder/snippet_syntax.ts
Remove the "generator" snippet interface.
We [removed support](https://github.com/cucumber/cucumber-js/pull/1725) for generators in steps some time ago.
- :boom: Breaking change (incompatible changes to the API)
----
> remove generator snippet interface

- docs/deprecations.md
- src/index.ts
- src/wrapper.mjs
- Some rewording and fixing around how we describe deprecations
- Undeprecate `defineStep` - at the time the direction seemed to be to eventually make [strict keywords](https://github.com/cucumber/common/issues/768) the only behaviour. However there is [not a consensus across platforms ](https://github.com/cucumber/cucumber-jvm/issues/2557#issuecomment-1137867515) for doing that, so on that basis it should only be an option. The `PickleStep` model [has an 'Unknown' value](https://github.com/cucumber/messages/blob/main/jsonschema/Pickle.json#L50) so we can use that for `defineStep` and just throw if you try to use it with strict keywords. Finally, a user raised [a separate concern](https://github.com/cucumber/cucumber-js/issues/2043#issuecomment-1267136955) in defense of `defineStep` from …
> deprecation updates ahead of 9.0.0

- package.json
Hi, sorry but I have been asked by my company to remove my work e-mail address from all public repos and this is one of them.
This was my mistake as I was accidentally using the wrong account when contributing to the project.
Cheers,
Scott
> remove my work e-mail from package.json

- CHANGELOG.md
- docs/formatters.md
- features/formatter_paths.feature
- package-lock.json
- package.json
- src/api/formatters.ts
- src/formatter/builder.ts
```
Scenario: Created relative path
When I run cucumber-js with `-f summary:some/long/path/for/reports/summary.txt`
Then the file "some/long/path/for/reports/summary.txt" has the text:
"""
1 scenario (1 passed)
1 step (1 passed)
<duration-stat>
"""
```
Previously Cucumber wouldn't created long directory chains as seen in this feature - some outside process had to make sure the directory the report file was to be written into exists.
Fixes #2159 
There was a test in place to see if Cucumber will fail if the directory didn't exist that was removed.  It is possible for this feature to fail if Cucumber lacks permission to create directories - but I feel testing this is a bit of overkill as such permission checking wasn't …
> Cucumber now creates whatever directories are necessary to make a report

- CHANGELOG.md
- src/models/data_table.ts
- :boom: Breaking change (incompatible changes to the API)
----
> change hashes type from any to Record<string, string>

- docs/transpiling.md
Clarified the differences between transpiling Cucumber in CommonJS and ESM
Spent 4 hours slogging through this.
Is this rewrite clear to others?
----
> 2243 clarify transpile.md

- CHANGELOG.md
- docs/installation.md
- src/cli/index.ts
- src/cli/install_validator.ts
- Tweak the wording of the global install warning to be less severe
- Only do the check and warning if debug is enabled
Fixes #2274 - since this can be a false positive, and the issues stemming from it are now [much more obvious and actionable](https://github.com/cucumber/cucumber-js/pull/2089) than they used to be, we don't need this to be prominent any more.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template …
> tone down global install warning

- CHANGELOG.md
- docs/formatters.md
- src/formatter/junit_formatter.ts
- src/formatter/junit_formatter_spec.ts
Added functionality which allows users to pass in custom test suite names for the Junit formatter
Fixes #2265 
I haven't added anything to the docs because I wasn't sure if there was a suitable place, but I am happy to write some documentation if it is needed :-). 
I added two unit tests, I tried to stick to the current format being used but I'm not entirely sure it's correct.
Finally there is a test failing under the 16x windows build. However it seems this test has failed in other PRs so I'm not sure it's related to the changes I've added. 
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-requ …
> Add option to pass in custom test suite name for Junit formatter

- CHANGELOG.md
- features/retry.feature
- src/formatter/rerun_formatter.ts
Referring to https://github.com/cucumber/cucumber-js/issues/2290
- `RerunFormatter` used to log failed attempts even if the attempt was retried. For example, it was possible that a testcase might have been fixed with one of the retry attempts, but still was logged due to earlier failing attempt. From now, `RerunFormatter` does not log attempts that are retried.
- Some minor quality of life changes for users who would like to `extends` `RerunFormatter`.
I am using `retry`  to stabilize tests of a distributed system. It was possible (for example right after a deployment), that the first couple of test attempts are failed against a service. I am also using `RerunFormatter` to log the failures. However, as `RerunFormatter` logged the failed attempts too, it was difficult to find out what …
> fix logFailedTestCases for RerunFormatter

- CHANGELOG.md
- compatibility/features/attachments/attachments.ts
- docs/support_files/attachments.md
- package-lock.json
- package.json
- src/formatter/helpers/issue_helpers_spec.ts
- src/formatter/helpers/test_case_attempt_formatter.ts
- src/runtime/attachment_manager/index.ts
- src/runtime/attachment_manager/index_spec.ts
- src/runtime/test_case_runner.ts
- test/fixtures/steps.ts
Add support for providing an optional filename for attachments, which is emitted as part of the `attachment` message and thus can be used in formatters.
To achieve this, we make the second argument to `this.attach` an options object, with backwards compatibility so a media type string still works as before.
Follow the cross-platform standards.
----
> support attachments with filenames

- CHANGELOG.md
- cucumber.json
- docs/formatters.md
- package-lock.json
- package.json
- src/api/convert_configuration.ts
- src/api/convert_configuration_spec.ts
- src/configuration/check_schema.ts
- src/configuration/types.ts
Expressing formats like `"html:./report.html"` is painful to read and write, and difficult for us to process. It gets worse when you want to include things that have colons, like URLs and Windows absolute file paths, some of which [we struggle to support smartly](https://github.com/cucumber/cucumber-js/pull/2315). It's unavoidable on the CLI but in a configuration file we can make it easier.
This PR adds support for a two-item array notation for format items, so for the above example you could instead do `["html", "./report.html"]`.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templa …
> better formats config

- CHANGELOG.md
- src/publish/publish_plugin.ts
Await the `finish` of the stream when cleaning up publish plugin.
Fixes #2321.
----
> wait for stream to finish at end of publish plugin

- CHANGELOG.md
- src/api/convert_configuration_spec.ts
- src/configuration/types.ts
When expressing a format as an array, support a single-item array in the typing.
If you want to use a formatter for stdout but with a local path containing colons etc, you may want to express that as a single item array to avoid Cucumber seeing the colon(s) and interpreting it as a formatter+target string to be broken apart. See https://github.com/webdriverio/webdriverio/pull/11010/files#r1309127113 for an example in the wild.
This worked anyway at runtime, but the types needed to reflect that, and some tests have been updated to prove it.
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templat …
> allow single-item arrays as a format

- .mocharc.yml
- src/api/load_support_spec.ts
- src/api/run_cucumber_spec.ts
Set timeouts on specific suites that take a long time, and set the default back to a reasonable 3s. Should reduce occasional Windows issues in CI.
> set timeouts appropriately

- CHANGELOG.md
- docs/configuration.md
- src/api/paths.ts
- src/api/paths_spec.ts
- src/configuration/validate_configuration.ts
Previously if you specified neither `require` nor `import` options, Cucumber would look under your feature directories for `.js` files and load them using `require()`. As part of our gradual move to the newer JavaScript modules system, we want to have that default behaviour use `await import()` instead.
This should be backwards-compatible for at least 99% of cases, since CommonJS code can still be loaded with `await import()`. The `require` option should only be needed when transpiling with `require-module` - although in those cases users are almost certainly specifying the `require` option already due the different file extensions like `.ts`. There's now a warning emitted if `require-module` values are provided but no `require` which should help guide users. Nevertheless we'll release …
> use import by default for support code

- CHANGELOG.md
- src/api/paths.ts
- src/api/paths_spec.ts
Change where we sort the list of expanded paths - do it for the results of each unexpanded path rather than once at the end for the whole result set, meaning the order of paths in the configuration is honoured.
Fixes #2343.
----
> honour order of paths in configuration

- .github/workflows/build.yaml
Remove now-defunct step that used to forcibly install npm 8. This was needed when 7 -> 8 changed a lockfile format, but now we can just go with whatever version is bundled with Node.js
> chore: remove defunct npm 8 step

- CHANGELOG.md
- features/world_parameters.feature
- src/configuration/types.ts
- src/runtime/index.ts
- src/runtime/parallel/worker.ts
- src/runtime/test_case_runner.ts
Clone the world parameters before creating each world instance. This prevents user code that updates the world parameters from leaking those changes across different test cases.
Also, type the `worldParameters` as `JsonObject` in configuration to enforce it should be JSON serialisable.
It would have been nice to somehow ensure immutability even between hooks/steps in the same test case. But realistically, users can have custom world instances, they can do what they want with the `parameters` object they are passed, so there's only so much we can do as the orchestrator.
Fixes #2356 
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-re …
> Prevent mutations on world parameters leaking between test cases

- CHANGELOG.md
- features/support/world.ts
- package-lock.json
- package.json
- src/cli/run.ts
- src/runtime/parallel/run_worker.ts
- src/runtime/run_test_run_hooks.ts
- src/try_require.ts
This PR removes `verror`, which was used to propagate errors with the original stack trace plus local context, as it is now unmaintained and is not tolerant of thrown objects that are not instances of `Error`.
Instead, we can make use of a newer native JavaScript feature, [`Error.cause`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause), to achieve the same thing.
Fixes #2359
----
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), …
> Replace usage of VError with Error.cause

- CHANGELOG.md
- exports/api/report.api.md
- src/api/load_configuration_spec.ts
- src/api/types.ts
- src/configuration/parse_configuration.ts
Further to https://github.com/cucumber/cucumber-js/pull/2373, the argv-style provided configuration should also support being an array of strings, as you might pull directly from `process.argv`.
----
> accept provided configuration as array of argv
